AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: tasks-app-backend

Globals:
  Function:
    Timeout: 3

Resources:
  GetTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_tasks/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - sg-0ba386509d49f41f9
        SubnetIds:
          - subnet-0523d0efcd24f849f
          - subnet-06c6c79d959f4a1f1
      Events:
        GetTasks:
          Type: Api
          Properties:
            Path: /tasks
            Method: get

Outputs:
  GetTasksApi:
    Description: "GET /tasks endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tasks/"

  GetTasksFunction:
    Description: "Get Tasks Lambda Function ARN"
    Value: !GetAtt GetTasksFunction.Arn
